"""teste de eclusão de campo

Revision ID: 834f3d92db5b
Revises: 7e338d4ddb91
Create Date: 2020-08-10 18:24:24.980562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834f3d92db5b'
down_revision = '7e338d4ddb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
