# .secrets.toml
# Este arquivo de config é lido pelo Dynaconf
# Ele contém as chaves que são secretas (tokens, senhas, etc.)
# Não deve ir para o repositório do Github (colocar no .gitignore)
# A melhor opção é usar um servidor de Vault
# Vide: https://www.twitch.tv/videos/697342703 (aos 02:32:03)

[default]
# Secret key pode ser gerada com: python -c "import os; print(os.urandom(16))"
#SECRET_KEY = "\xe8\xa8\xb9\xe5Q\x9d;\x93\x8c\xd4.\xb1T\x93\x06\x81"
SECRET_KEY = ",sdandanslkxlkkjhe#$*&(*iuIUI&GKJGI8oiooi135876939420"

